version: 2
jobs:
  build:
    docker:
      - image: elixir:1.5.2
        environment:
          MIX_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix test
